project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "FAIR Research Data Management"
  navbar:
    left:
      - href: slides.html
        text: "Slides"

format:
  revealjs:
    scrollable: true
    smaller: true
    auto-stretch: false